routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');	
});

// Mobile API
Route::get('api/log', 'ApiController@api_log')->name('api_log');
Route::get('api/log/update', 'ApiController@log_update')->name('log_update');
Route::get('qr/{size}/{format}/{key}', 'ApiController@qr')->name('qr');
Route::get('card/{id}', 'ApiController@school_card')->name('card');

Auth::routes();

// admin routes
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('print', 'HomeController@print_report')->name('print');

// settings
Route::get('settings', 'SettingsController@index')->name('settings');
Route::post('settings/profile', 'SettingsController@profile_update')->name('profile.update');
Route::post('settings/password', 'SettingsController@password_update')->name('password.update');

// Restful Controllers
Route::resources([
	'users' => 'UsersController',
	'roles' => 'RolesController',
	'members' => 'MembersController',
]);

app/Http/Controllers/MembersController.php
<?php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Log;
use App\Member;
use Validator;
use Storage;
use Image;

class MembersController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

        $this->params = array(
            'title' => 'Members',
            'description' => 'Manage all members.',
        );

        $this->validate = array(
            // 'photo' => 'required|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'middle_name' => 'required|string|max:255',
            'gender' => 'required|string|max:255',
            'birthdate' => 'required|string|max:255',
            'address' => 'required|string|max:255',
            'phone_number' => 'required|string',
            'active' => 'boolean',
        );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index( Request $request )
    {

        $search = ( $request->input('search') ) ? $request->input('search'): '';
        $perpage = preg_replace('/\D/', '', $request->input('show') );
        $show = ( empty( $perpage ) || $perpage == 0 ) ? 10: $perpage;

        $members = Member::orderBy('first_name','asc');

        $where = [];
        
        if ( $search ) { 

            $where[] = ['first_name', 'LIKE', "%$search%"];

            $members->where( $where );
            $members->orWhere('last_name', 'LIKE', "%$search%");
            $members->orWhere('middle_name', 'LIKE', "%$search%");
            
        } else {

            $members->where( $where );
        }

        $this->params['search']     = $search;
        $this->params['perpage']    = $show;
        $this->params['members']   = $members->paginate( $show );

        return view('members.index', $this->params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->params['title'] = 'Register new member';
        $this->params['description'] = 'Customize and register new member account.';

        return view('members.create', $this->params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Block members who are not admin
        $request->user()->authorizeRoles('admin');

        $validator = Validator::make( $request->all(), $this->validate );

        if ( $validator->fails() ) {
            return redirect('members/create')
                ->withErrors( $validator )
                ->withInput();
        }

        $member = new Member();
        $member->fill( $request->all() );

        if ( $request->hasFile('photo') ) {

            if ( !$request->file('photo')->isValid() ) {
                return redirect('members/create')->withInput()->with('error', 'The photo you uploaded is invalid.');
            }

            $fname =  str_replace(' ', '_', $request->input('first_name').'_'.$request->input('last_name') );
            $directory = public_path() . '/uploads/';
            $filename = strtolower( $fname ) . '.' . $request->photo->extension();
            $upload_path = $directory . $filename;
            Image::make( $request->photo )->fit(130, 130, function ($constraint) {
                $constraint->upsize();
            })->save( $upload_path );

            $member->photo = $filename;
        }

        $member->card_number = $this->randomNumber(15);
        $member->save();

        return redirect('members')->with('success', 'Member ' . $member->first_name . ' successfuly added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $this->params['title'] = 'Edit Member Info';
        $this->params['description'] = 'Update member information.';

        $member = Member::find( $id );

        if ( ! $member ) {
            return redirect('members')->with('warning', 'Member no longer exist.');
        }

        $this->params['member'] = $member;
        $this->params['photo'] = 'uploads/'.$member->photo;

        return view('members.edit', $this->params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update( Request $request, $id )
    {

        // Block members who are not admin
        $request->user()->authorizeRoles('admin');

        $member = Member::find( $id );

        // double check if member exist.
        if ( ! $member ) {
            return redirect('members')->with('error', 'member does not exist, please try again.');
        }

        $validator = Validator::make( $request->all(), $this->validate );

        if ( $validator->fails() ) {
            return redirect('members/'. $member->id .'/edit')
                ->withErrors( $validator )
                ->withInput();
        }

        if ( $request->hasFile('photo') ) {

            if ( !$request->file('photo')->isValid() ) {
                return redirect('members/create')->withInput()->with('error', 'The photo you uploaded is invalid.');
            }

            $fname =  str_replace(' ', '_', $request->input('first_name').'_'.$request->input('last_name') );
            $directory = public_path() . '/uploads/';
            $filename = strtolower( $fname ) . '.' . $request->photo->extension();
            $upload_path = $directory . $filename;

            Image::make( $request->photo )->fit(130, 130, function ($constraint) {
                $constraint->upsize();
            })->save( $upload_path );

            $member->photo = $filename;
        }

        $member->fill( $request->all() );
        $member->save();

        return redirect('members/'. $member->id .'/edit')->with('success', 'Member details successfuly updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Request $request, $id )
    {
        // Block members who are not admin
        $request->user()->authorizeRoles('admin');

        $member = Member::find( $id );

        if ( ! $member ) {
            return response()->json([
                'error' => true,
                'message' => 'Please try again.'
            ]);
        } 

        $logs = Log::where('user_id','=',$member->id)->get();
        foreach ($logs as $log) {
            $log->delete();
        }

        $member->delete();

        return response()->json([
            'error' => false,
            'message' => 'Member successfuly removed.'
        ]);
    }

    public function randomNumber($length) {
        $result = '';

        for($i = 0; $i < $length; $i++) {
            $result .= mt_rand(0, 9);
        }

        return $result;
    }
}

resources/views/members/create.blade.php
@extends('admin')

@section('content')

<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">Add member</div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		
		<form action="{{ route('members.store') }}" method="POST" enctype="multipart/form-data" role="form">
			{{ csrf_field() }}

			<div class="row">
				
				<div class="col-md-6">

					<div class="form-group">
						<label for="photo">Photo</label>
						<input type="file" value="{{ old('photo') }}" name="photo" class="form-control" id="photo" placeholder="Address">
					</div>

					<label for="birthday">Birth Day</label>
					<div class="input-group date" style="direction: rtl;">
                        <input type="text" value="{{ old('birthdate') }}" placeholder="{{ date('m/d/Y') }}" name="birthdate" id="birthdate" class="form-control">
                        <span class="input-group-addon">
                        	<i class="fa fa-calendar"></i>
                        </span>
                    </div>
                    <br>

					<div class="form-group">
						<label for="address">Address</label>
						<input type="text" value="{{ old('address') }}" name="address" class="form-control" id="address" placeholder="Address">
					</div>

					<div class="form-group">
						<label for="phone_number">Phone Number</label>
						<input type="text" value="{{ old('phone_number') }}" name="phone_number" class="form-control" id="phone_number" placeholder="Phone Number">
					</div>

					<label for="renewal_date">Valid Until</label>
					<div class="input-group date" style="direction: rtl;">
                        <input type="text" value="{{ old('renewal_date') ? old('renewal_date'):date('m/d/Y', strtotime('+5 years')) }}" placeholder="{{ date('m/d/Y') }}" name="renewal_date" id="renewal_date" class="form-control">
                        <span class="input-group-addon">
                        	<i class="fa fa-calendar"></i>
                        </span>
                    </div>
                    <br>
					
					<button type="submit" class="btn btn-primary">Save member <i class="fa fa-save"></i></button>
				</div>

				<div class="col-md-6">

					<div class="form-group">
						<label for="first_name">First Name</label>
						<input type="text" value="{{ old('first_name') }}" name="first_name" class="form-control" id="first_name" placeholder="First name">
					</div>

					<div class="form-group">
						<label for="last_name">Last Name</label>
						<input type="text" value="{{ old('last_name') }}" name="last_name" class="form-control" id="last_name" placeholder="Last name">
					</div>

					<div class="form-group">
						<label for="middle_name">Middle Name</label>
						<input type="text" value="{{ old('middle_name') }}" name="middle_name" class="form-control" id="middle_name" placeholder="Middle name">
					</div>

					<div class="form-group">
						<label for="gender">Gender</label>
						<select name="gender" class="form-control" id="gender">
							<option value="male"{{ old('gender')=='male' ? ' selected':'' }}>Male</option>
							<option value="female"{{ old('gender')=='female' ? ' selected':'' }}>Female</option>
						</select>
					</div>

					<div class="form-group">
						<label for="name">Activate Member</label><br>
						<input type="checkbox" name="active" value="1" class="js-switch" {{ old('active') ? 'checked':'' }} />
						<span id="active-status">Active</span>
					</div>

				</div>
			</div>
		
		</form>
		
	</div>
</div>

@endsection

@section('action')
<div class="title-action">
<a href="{{ route('members.index') }}" class="btn btn-white">
	Back <i class="fa fa-chevron-left"></i> 
</a>
</div>
@endsection

@section('styles')
<link href="{{asset('css/plugins/iCheck/custom.css')}}" rel="stylesheet">
<link rel="stylesheet" href="{{asset('assets/js/daterangepicker/daterangepicker-bs3.css')}}">
<link href="{{asset('css/plugins/switchery/switchery.css')}}" rel="stylesheet">
<style>.datepicker{right:auto;}</style>
@endsection

@section('scripts')
<script src="{{asset('js/plugins/datapicker/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('js/plugins/switchery/switchery.js')}}"></script>
<script>
	jQuery(document).ready(function($) {
		$('#birthdate, #renewal_date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });
        var switchBtn = document.querySelector('.js-switch');
        var switchButton = new Switchery(switchBtn, { color: '#1AB394' });
        switchBtn.onchange = function() {
        	if ( switchBtn.checked ) {
        		$('.js-switch').attr('checked','checked');
        		$('#active-status').text('Active');
        	} else {
        		$('.js-switch').removeAttr('checked');
        		$('#active-status').text('Inactive');
        	}
		};
	});
</script>
@endsection

resources/views/members/edit.blade.php
@extends('admin')

@section('content')

<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">Add member</div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		
		<form action="{{ route('members.update', $member->id) }}" method="POST" enctype="multipart/form-data" role="form">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="PUT">
			<div class="row">
				
				<div class="col-md-6">
					

					<div class="row">
						<div class="col-md-7 col-sm-7 col-xs-12">

							<label for="birthday">Birth Day</label>
							<div class="input-group date" style="direction: rtl;">
		                        <input type="text" value="{{ $member->birthdate }}" placeholder="{{ date('m/d/Y') }}" name="birthdate" id="birthdate" class="form-control">
		                        <span class="input-group-addon">
		                        	<i class="fa fa-calendar"></i>
		                        </span>
		                    </div>
		                    <br>

							<div class="form-group">
								<label for="address">Address</label>
								<input type="text" value="{{ $member->address }}" name="address" class="form-control" id="address" placeholder="Address">
							</div>

							<div class="form-group">
								<label for="phone_number">Phone Number</label>
								<input type="text" value="{{ $member->phone_number }}" name="phone_number" class="form-control" id="phone_number" placeholder="Phone Number">
							</div>

							<label for="renewal_date">Valid Until</label>
							<div class="input-group date" style="direction: rtl;">
		                        <input type="text" value="{{ $member->renewal_date }}" placeholder="{{ date('m/d/Y') }}" name="renewal_date" id="renewal_date" class="form-control">
		                        <span class="input-group-addon">
		                        	<i class="fa fa-calendar"></i>
		                        </span>
		                    </div>
		                    <br>
		                    <button type="submit" class="btn btn-primary btn-lg">Save member <i class="fa fa-save"></i></button>
						</div>
						<div class="col-md-4 col-sm-4 col-xs-12">

							@if( $photo )
								<img src="{{ asset($photo) }}" class="img-responsive" alt="">
							@endif

							<div class="form-group">
								<label for="photo">Photo</label>
								<input type="file" value="" name="photo" class="form-control" id="photo" placeholder="Address">
							</div>	
							
						</div>
					</div>

				</div>

				<div class="col-md-6">

					<div class="form-group">
						<label for="first_name">First Name</label>
						<input type="text" value="{{ $member->first_name }}" name="first_name" class="form-control" id="first_name" placeholder="First name">
					</div>

					<div class="form-group">
						<label for="last_name">Last Name</label>
						<input type="text" value="{{ $member->last_name }}" name="last_name" class="form-control" id="last_name" placeholder="Last name">
					</div>

					<div class="form-group">
						<label for="middle_name">Middle Name</label>
						<input type="text" value="{{ $member->middle_name }}" name="middle_name" class="form-control" id="middle_name" placeholder="Middle name">
					</div>

					<div class="form-group">
						<label for="gender">Gender</label>
						<select name="gender" class="form-control" id="gender">
							<option value="male"{{ $member->gender=='male' ? ' selected':'' }}>Male</option>
							<option value="female"{{ $member->gender=='female' ? ' selected':'' }}>Female</option>
						</select>
					</div>

					<div class="form-group">
						<label for="name">Activate Member</label><br>
						<input type="checkbox" name="active" value="1" class="js-switch" {{ $member->active ? 'checked':'' }} />
						<span id="active-status">Active</span>
					</div>

				</div>
			</div>
		
		</form>
		
	</div>
</div>

@endsection

@section('action')
<div class="title-action">
<a href="{{ route('members.index') }}" class="btn btn-white">
	Back <i class="fa fa-chevron-left"></i> 
</a>
</div>
@endsection

@section('styles')
<link href="{{asset('css/plugins/iCheck/custom.css')}}" rel="stylesheet">
<link rel="stylesheet" href="{{asset('assets/js/daterangepicker/daterangepicker-bs3.css')}}">
<link href="{{asset('css/plugins/switchery/switchery.css')}}" rel="stylesheet">
<style>.datepicker{right:auto;}</style>
@endsection

@section('scripts')
<script src="{{asset('js/plugins/datapicker/bootstrap-datepicker.js')}}"></script>
<script src="{{asset('js/plugins/switchery/switchery.js')}}"></script>
<script>
	jQuery(document).ready(function($) {
		$('#birthdate, #renewal_date').datepicker({
            todayBtn: "linked",
            keyboardNavigation: false,
            forceParse: false,
            calendarWeeks: true,
            autoclose: true
        });
        var switchBtn = document.querySelector('.js-switch');
        var switchButton = new Switchery(switchBtn, { color: '#1AB394' });
        switchBtn.onchange = function() {
        	if ( switchBtn.checked ) {
        		$('.js-switch').attr('checked','checked');
        		$('#active-status').text('Active');
        	} else {
        		$('.js-switch').removeAttr('checked');
        		$('#active-status').text('Inactive');
        	}
		};
	});
</script>
@endsection

resources/views/members/logs.blade.php
@extends('admin')

@section('content')

<div class="row">
	<div class="col-sm-3 col-xs-6">
		<div class="tile-stats tile-red">
			<div class="icon"><i class="entypo-users"></i></div>
			<div class="num" data-start="0" data-end="{{ $member_count }}" data-postfix="" data-duration="1500" data-delay="0">{{ $member_count }}</div>
			<h3>Registered members</h3>
		</div>
	</div>

	<div class="col-sm-3 col-xs-6">

		<div class="tile-stats tile-green">
			<div class="icon"><i class="entypo-chart-bar"></i></div>
			<div class="num" data-start="0" data-end="{{ $logs_count }}" data-postfix="" data-duration="1500" data-delay="600">{{ $logs_count }}</div>
			<h3>Daily Logs</h3>
		</div>

	</div>
</div>

<br>
<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">Recent logs</div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		
		<div class="row">

			<div class="col-md-6">
				<form action="{{ route('print') }}" method="GET" class="form-horizontal form-groups-bordered" role="form" style="direction: rtl;">
				
					<input type="hidden" name="start_date" value="">
					<input type="hidden" name="end_date" value="">
					
					<div class="form-group">
						<label class="col-sm-3 control-label">
							Select Date Range:
						</label>
						
						<div class="col-sm-5">
							<div class="daterange daterange-inline" data-format="MMMM D, YYYY" data-start-date="{{ date('F d, Y') }}" data-end-date="{{ date('F d, Y') }}">
								<i class="entypo-calendar"></i>
								<span>{{ date('F d, Y') }} - {{ date('F d, Y') }}</span>
							</div>
						</div>
						<div class="col-md-3">
							<button type="submit" class="btn btn-primary btn-md">Print Report <i class="fa fa-print"></i></button>
						</div>
					</div>

				</form>
			</div>
			
			<div class="col-md-6">
				
				<form action="{{ route('home') }}" method="GET" class="form-inline pull-left" role="form" style="direction: ltr;">

					<div class="input-group">
						<span class="input-group-addon">Per page</span> 
						<input type="number" name="show" style="width: 80px;" placeholder="10" value="{{ $perpage }}" class="form-control">
						<span class="input-group-btn"> 
							<button type="submit" class="btn btn-info" style="margin: 0;">GO</button>
						</span>

					</div>
				</form>
				
			</div>
			
		</div>

		<hr>
		
		@if( $logs->count() )
			
		<div class="table-responsive">
			<table class="table table-bordered table-striped table-hover">
				<thead>
					<tr>
						<th><strong>Name</strong></th>
						<th><strong>Vehicle</strong></th>
						<th><strong>Plate Number</strong></th>
						<th><strong>Department</strong></th>
						<th><strong>Visitor</strong></th>
						<th><strong>Purpose</strong></th>
						<th><strong>Log Type</strong></th>
						<th><strong>Time</strong></th>
					</tr>
				</thead>
				<tbody>
					@foreach( $logs as $log )

						@if($log->user())
						<tr id="user-row-{{ $log->id }}">
							<td>
								<a href="{{ route('users.edit',$log->user()->id) }}">
									{{ $log->user()->first_name.' '.$log->user()->last_name }}
								</a>
							</td>
							<td>{{ $log->user()->vehicle_type.' ('.$log->user()->vehicle_model.')' }}</td>
							<td>{{ $log->user()->plate_number }}</td>
							<td>{{ $log->user()->school }}</td>
							<td>{{ ($log->user()->visitor) ? 'Yes':'No' }}</td>
							<td>{{ $log->purpose }}</td>
							<td>{{ $log->log_type }}</td>
							<td>{{ date( 'M d, Y h:i a', strtotime( $log->created_at ) ) }}</td>
						</tr>
						@endif

					@endforeach
				</tbody>
			</table>
		</div>
		{!! $logs->appends( request()->input() )->links() !!}
		@else
		<div class="alert alert-info">
			<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
			<strong>No records to show at the moment.</strong>
		</div>
		@endif
	</div>
</div>

<div class="modal inmodal" id="remove-user" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Remove Member</h4>
            </div>
            <div class="modal-body">
                <p><strong>Are you sure?</strong> once removed, this user will no longer be able to login on his/her account and all data affiliated to this account will be deleted.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="pull-right btn btn-white"  data-dismiss="modal">Cancel</button>

                <button type="button" id="remove-btn" class="btn btn-danger">Remove</button>
            </div>
        </div>
    </div>
</div>

<div id="print-id" style="">
	
</div>

@endsection

@section('action')

@endsection

@section('styles')
<!-- Toastr style -->
<link href="{{asset('css/plugins/toastr/toastr.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/js/daterangepicker/daterangepicker-bs3.css')}}" rel="stylesheet">
<style>
	.daterangepicker{
		direction: ltr;
	}
</style>
@endsection

@section('scripts')

<script src="{{asset('assets/js/moment.min.js')}}"></script>
<script src="{{asset('assets/js/daterangepicker/daterangepicker.js')}}"></script>
<!-- Toastr script -->
<script src="{{asset('js/plugins/toastr/toastr.min.js')}}"></script>
<script>
jQuery(document).ready(function() {

	// Date Range Picker
	if($.isFunction($.fn.daterangepicker))
	{
		$(".daterange").each(function(i, el)
		{
			// Change the range as you desire
			var ranges = {
				'Today': [moment(), moment()],
				'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
				'Last 7 Days': [moment().subtract('days', 6), moment()],
				'Last 30 Days': [moment().subtract('days', 29), moment()],
				'This Month': [moment().startOf('month'), moment().endOf('month')],
				'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
			};

			var $this = $(el),
				opts = {
					format: attrDefault($this, 'format', 'MM/DD/YYYY'),
					timePicker: attrDefault($this, 'timePicker', false),
					timePickerIncrement: attrDefault($this, 'timePickerIncrement', false),
					separator: attrDefault($this, 'separator', ' - '),
				},
				min_date = attrDefault($this, 'minDate', ''),
				max_date = attrDefault($this, 'maxDate', ''),
				start_date = attrDefault($this, 'startDate', ''),
				end_date = attrDefault($this, 'endDate', '');

			if($this.hasClass('add-ranges'))
			{
				opts['ranges'] = ranges;
			}

			if(min_date.length)
			{
				opts['minDate'] = min_date;
			}

			if(max_date.length)
			{
				opts['maxDate'] = max_date;
			}

			if(start_date.length)
			{
				opts['startDate'] = start_date;
			}

			if(end_date.length)
			{
				opts['endDate'] = end_date;
			}


			$this.daterangepicker(opts, function(start, end)
			{
				var drp = $this.data('daterangepicker');

				if($this.is('[data-callback]'))
				{
					//daterange_callback(start, end);
					callback_test(start, end);
				}

				if($this.hasClass('daterange-inline'))
				{
					$this.find('span').html(start.format(drp.format) + drp.separator + end.format(drp.format));
				}
			});
		});

		$('.daterange').on('apply.daterangepicker', function(ev, picker) {
			$('[name="start_date"]').val( picker.startDate.format('MM/DD/YYYY') );
			$('[name="end_date"]').val( picker.endDate.format('MM/DD/YYYY') );
		});
	}

	toastr.options = {
		"closeButton": true,
		"debug": false,
		"progressBar": true,
		"positionClass": "toast-top-right",
		"onclick": null,
		"showDuration": "400",
		"hideDuration": "1000",
		"timeOut": "7000",
		"extendedTimeOut": "1000",
		"showEasing": "swing",
		"hideEasing": "linear",
		"showMethod": "fadeIn",
		"hideMethod": "fadeOut"
	}

	jQuery('button[data-name="delete"]').click(function(e) {
		e.preventDefault();
		var token = jQuery('meta[name="csrf-token"]').attr('content');
	});

	jQuery('#remove-user').on('show.bs.modal', function (event) {
		var button = jQuery(event.relatedTarget); // Button that triggered the modal
		var user_id = button.data('id');
		jQuery('#remove-btn').data('id',user_id);
  		jQuery(this).find('.modal-title').text('Remove ' + jQuery('#user-row-'+user_id+' td:first').html() );
	});

	jQuery('#user-qrcode').on('show.bs.modal', function (event) {

		var button = jQuery(event.relatedTarget); // Button that triggered the modal
		var hash = button.data('hash');
		var card = button.data('card');

		jQuery('#qrcode-img').attr('src', '{{ url('/') }}/qr/250/png/'+hash);

		var data = button.data('json');
		var html = '<b>ID:</b> '+data.card_number+'<br>';
		html += '<b>First Name:</b> '+data.first_name+'<br>';
		html += '<b>Middle Name:</b> '+data.middle_name+'<br>';
		html += '<b>Last Name:</b> '+data.last_name+'<br>';
		html += '<b>Gender:</b> '+data.gender+'<br>';
		html += '<b>Birth Day:</b> '+data.birthdate+'<br>';
		html += '<b>Address:</b> '+data.address+'<br>';
		html += '<b>Phone Number:</b> '+data.phone_number+'<br>';

  		jQuery(this).find('#user-info').html( html );
  		jQuery('#card-link').attr('href',card);

	});

	jQuery('#remove-btn').click(function(e) {
		e.preventDefault();
		var user_id = jQuery(this).data('id');
		var token = jQuery('meta[name="csrf-token"]').attr('content');

		jQuery.ajax({  
			url: '{{ route('members.index') }}/'+user_id,
			type: 'POST',
			dataType: 'json',
			data: { _token: token, _method: 'DELETE' },
		})
		.always(function(data) {
			if (data.error) {
				toastr.error(data.message,'Error');
			} else {
				jQuery('#remove-user').modal('toggle');
				toastr.success(data.message,'Success');
				jQuery('#user-row-'+user_id).remove();
			}
		});
		 
	});
});
</script>
@endsection